### ISSUE TITLE
Describe libraries used.

### ISSUE THREAD

**Issue by emiliakaf** [amosproj/amos2021ws02-agile-trans-jira#103]
As we have presented a new code structure in order to implement a planner, we need to describe the code structure and also the libraries used

**Comment by emiliakaf** [comment]
Hi @Stefuniverse, could you assist me on this task because you have the most knowledge on the new code structure?

**Comment by Stefuniverse** [comment]
sure, before the next release meeting or after? I could go with 8am tommorow morning, otherwise just schedule abmeeting with me.
