### ISSUE TITLE
Transformation of the extracted data to the frontend

### ISSUE THREAD

**Issue by woxihyc** [amosproj/amos2021ws02-agile-trans-jira#118]
We could extract requests of current assignee #82 and we need to deliver the information to the frontend. The information does not need to fit in the calendar yet. Showing the issue list is enough.

## User story
1. As a user
2. I want to check my schedule on the website
3. So that I know what tasks to do

## Acceptance criteria
* Deliver the data extracted from #82 to the frontend
* Display the information in the frontend

## Definition of done
* Can be demoed
* Fully tested with the unit test
* Code well structured and formatted (hold to code conventions)
* Clear explanations of code
* No syntax/runtime errors
* Codes are peerly reviewed
* Communicate issues by leaving comments on Github

**Comment by romankupkovic** [comment]
issues show up in calendar,
formatting of time start and end points is not optimal,

**Comment by emiliakaf** [comment]
problem with customfields id has been solved: implementation was merged with pull request #140 and tested at more than two computers
