### ISSUE TITLE
Complete the Manual test

### ISSUE THREAD

**Issue by woxihyc** [amosproj/amos2021ws02-agile-trans-jira#138]
Some entries remain unfilled in the Github wiki, we need to complete them.

## User story
1. As a user
2. I want to have a complete manual test guide
3. So that I could test the system

## Acceptance criteria
* no empty entries left in manual test
* the guidance are clear and correct

## Definition of done
* Can be demoed
* Fully tested with the unit test
* Code well structured and formatted (hold to code conventions)
* Clear explaination of code
* No syntax/runtime errors
* Codes are peerly reviewed
* Communicate issues by leaving comments on github

**Comment by emiliakaf** [comment]
described tests of personal calendar and use basic search
