### ISSUE TITLE
Create roadmap

### ISSUE THREAD

**Issue by mdp97** [amosproj/amos2021ws02-agile-trans-jira#29]
Create calendar which will be implemented on the main page. No functionality necessary yet. Document which information would be necessary to represent the requests in the calendar. See #37 

## User story
1. As a user I want to have an overview over my calender and requests
2. I need an overview on the accepted/pending requests
3. So that I can manage the open requests

## Acceptance criteria
* Visual overview on the requests per team

## Definition of done
* Can be demoed
* Fully tested with the unit test
* Code well structured and formatted (hold to code conventions)
* Clear explaination of code
* No syntax/runtime errors
* Codes are peerly reviewed
* Communicate issues by leaving comments on github

<img width="844" alt="Screen Shot 2021-11-10 at 20 50 52" src="https://user-images.githubusercontent.com/28757096/141183363-0a1dff25-abd7-47f3-a209-623feb65efed.png">

**Comment by emiliakaf** [comment]
will continuied with bug
