### ISSUE TITLE
Create "create request"-screen

### ISSUE THREAD

**Issue by mdp97** [amosproj/amos2021ws02-agile-trans-jira#30]
Use the mock-up of bearing point and our mockup to create a create request screen. This is supposed to be our initial draft for the next industry partner meeting. Document which information would be necessary to create a request.

If possible try to use active objects to add first functionality to our product. In this case we would store some data of the request in our database as well as storing things in Jira. 

## User story
1. As a product owner
2. I want create a request and request ressources with it
3. So that I can fulfill the projects requirements

## Acceptance criteria

- [ ] Skeleton on a create request screen
- [ ] Being able to retrieve the saved data from the database
- [ ]  Standard fields only

## Definition of done
* Can be demoed
* Fully tested with the unit test
* Code well structured and formatted (hold to code conventions)
* Clear explaination of code
* No syntax/runtime errors
* Codes are peerly reviewed
* Communicate issues by leaving comments on github

**Comment by teanas** [comment]
Created merge request #74

**Comment by teanas** [comment]
Real 5 due to an extra implemented task - retrieving existing *Request* issue type ID to be able to open a correct "Create request" tab
