### ISSUE TITLE
Team information

### ISSUE THREAD

**Issue by mdp97** [amosproj/amos2021ws02-agile-trans-jira#33]
What information about the teams will be needed? Can we retrieve certain information from Jira?

Document information and create dummy data for future developments.

## User story
1. As a product owner
2. I need an overview on the existing teams and their availability
3. So that I can address requests to the right team

## Acceptance criteria
* Criterion 1
* Criterion 2

## Definition of done
* Added only after week 5
* The same for all features

**Comment by romankupkovic** [comment]
[Team Information.pdf](https://github.com/amosproj/amos2021ws02-agile-trans-jira/files/7641558/Team.Information.pdf)
