### ISSUE TITLE
Create project settings page 

### ISSUE THREAD

**Issue by mdp97** [amosproj/amos2021ws02-agile-trans-jira#42]
## User story
1. As a product owner
2. I want have an setting over the project in the plugin
3. So that I can model the project structure inside the plugin

## Acceptance criteria
* Criterion 1
* Criterion 2
* ...

## Definition of done
* Added only after week 5
* The same for all features

**Comment by teanas** [comment]
@mdp97 which settings exactly are expected to be configurable here? only *Enable Planner for the Project* & *Check Project Compatibility* (as per mockup https://docs.google.com/document/d/1kryYVnLDnkynQrUmu13G6sUjypJvnNzcW-GSgJ5Gg1w/edit )?

**Comment by teanas** [comment]
same question to @thumy-huynh

**Comment by teanas** [comment]
Merged branch  #feature_project_settings #52
