### ISSUE TITLE
"Advanced" request overview

### ISSUE THREAD

**Issue by mdp97** [amosproj/amos2021ws02-agile-trans-jira#47]
According to proposal from @emiliakaf 
## User story
1. As a {}
2. I want / need {}
3. So that {}

## Acceptance criteria
* Criterion 1
* Criterion 2
* ...

## Definition of done
* Added only after week 5
* The same for all features

**Comment by romankupkovic** [comment]
Progress:
- the request overview button on the left sidebar links to the jira native issue search (workaround)
- the dropdown buttons in the request overview tab view are showing the dropdown menus on click (design like the jira native issue search)
- the jql advanced search toggle works and toggles between the basic button filter search and the jql input form

remaining:
- alignment of the items needs improvement
- list / details view switch function for the result table not implemeted, yet
