### ISSUE TITLE
Create screen for general plugin setting

### ISSUE THREAD

**Issue by mdp97** [amosproj/amos2021ws02-agile-trans-jira#55]
Create a screen for general plugin setting which are accessible through the "manage apps" section in the Jira settings (Admin view)

## User story
1. As a Mira system administrator
2. I want to customize the app
3. So that it fits the needs of my company's users.

## Acceptance criteria
* Visible screen with all the button in the jira settings
* ...

## Definition of done
* Can be demoed
* Fully tested with the unit test
* Code well structured and formatted (hold to code conventions)
* Clear explaination of code
* No syntax/runtime errors
* Codes are peerly reviewed
* Communicate issues by leaving comments on github

**Comment by emiliakaf** [comment]
These general settings should be accessible through the Administration (the gear button top right) -Manage Apps.
You can see the suggested position and and example of administration of a plugin in the screenshot.
You can already create placeholders for the sections planned (see mockup https://docs.google.com/document/d/1kryYVnLDnkynQrUmu13G6sUjypJvnNzcW-GSgJ5Gg1w/edit)
Suggested name: Agile Planning Plugin. Another ideas are welcome :) 
![image](https://user-images.githubusercontent.com/92568413/144321034-7173d8c1-5e14-48c9-8206-0445d3f9cc2d.png)

**Comment by emiliakaf** [comment]
Additional acceptance criteria:

- [ ] When clicking on Administration - Manage apps a system administrator finds the Agile Planing Platform section
