### ISSUE TITLE
Create custom fields in general settings

### ISSUE THREAD

**Issue by emiliakaf** [amosproj/amos2021ws02-agile-trans-jira#62]
### User Story
As a sytem administrator
I want to see the available custom fields of the plugin
so that they can be used in a create screen.

### Description
In order to use custom fields in the create screen, we need to create them. First goal is that they are managed in the general settings location. Create following custom fields. Try to use standard field types. Fields should be locked and not changable (nice to have)

- Requested Team: in this field the user directly searches for the requested team. Results to be shown in a drop down
- Requested Time span: select start and end date (behaviour similar to flight search)

### Acceptance Criteria

- [ ] - Three custom fields are available in the general settings of the plugin and can be used in a create screen of choice

### Definition of Done
* Can be demoed
* (Fully tested with the unit test)
* Code well structured and formatted (hold to code conventions)
* Clear explaination of code
* No syntax/runtime errors
* Codes are peerly reviewed
* Communicate issues by leaving comments on github

**Comment by romankupkovic** [comment]
mistyped commit message.
--
added class GeneralSettingsCf.java for custom field implementation.
added customfield block to atlassian-plugin.xml.

Right now GeneralSettingsCf.java just implements a basic custom field of type GenericTextCFType.
Prepared google docs for some information I collected during the task.

[customFieldsGeneralSettings.pdf](https://github.com/amosproj/amos2021ws02-agile-trans-jira/files/7723202/customFieldsGeneralSettings.pdf)
