### ISSUE TITLE
Create issue type request

### ISSUE THREAD

**Issue by emiliakaf** [amosproj/amos2021ws02-agile-trans-jira#64]
### User Story
As a user 
I want to be able to use the issue type "Request" 
so that I can create capacity requests on teams.

### Description
In the general settings page , the issue type Request should be available right after installing the plugin. In this way there are no further configurations needed by the system administrator.

### Acceptance Criteria

- [ ]  By clicking on Administration ->Manage Apps ->Agile Planning Platforms -> General Settings -> Request Management Issue Types the issue type Request is available by default

- [x] Request type has following attributes: Name , Description, ID

### Definition of Done

Can be demoed
(Fully tested with the unit test)
Code well structured and formatted (hold to code conventions)
Clear explaination of code
No syntax/runtime errors
Codes are peerly reviewed
Communicate issues by leaving comments on github

**Comment by emiliakaf** [comment]
will be proceeded in sprint 09, not able to be tested with the current structure

**Comment by teanas** [comment]
Does not work to create request type on start

**Comment by teanas** [comment]
Found a solution - need a different interface for Creating issue types on init ([see](https://community.developer.atlassian.com/t/on-jira-starting-defaultissuetypemanager-creationlock-is-null-when-pluginenabledevent-is-published/29921]))
