### ISSUE TITLE
Implement a JQL search in Request Overview Tab

### ISSUE THREAD

**Issue by emiliakaf** [amosproj/amos2021ws02-agile-trans-jira#66]
In #36 we have implemented the visual representation of the Request Overview Tab. The search is part of it. As first step we could implement the JQL search. To test the feature you could create an issue on your own in the jira instance and then search for it through the JQL search.

## User story
1. As a user
2. I want to be able to use the JQL search in the Request Overview Tab
3. So that I can be able to write JQL queries and find needed issues

## Acceptance criteria

- [ ] JQL query of reporter = currentUser () gives back all of the created issues in the current jira instance by me

## Definition of done

- Can be demoed
- Fully tested with the unit test
- Code well structured and formatted (hold to code conventions)
- Clear explaination of code
- No syntax/runtime errors
- Codes are peerly reviewed
- Communicate issues by leaving comments on github

**Comment by mdp97** [comment]
For JQL Queries we need to figure out how we handle REST Requests. I’d need another sprint for this issue.

**Comment by mdp97** [comment]
@emiliakaf The handling of the non-JQL requests in the request overview will most likely also be done via REST-Requests. We may need to find a way to link separate JavaScript files into the Velocity-Templates for better overview in the code.

**Comment by emiliakaf** [comment]
Hey @mdp97 
putting back in Produckt backlog JQL field needs to be implemented (auto complete) and bug of search button
