### ISSUE TITLE
Add Manual Frontend tests

### ISSUE THREAD

**Issue by emiliakaf** [amosproj/amos2021ws02-agile-trans-jira#81]
## User story
1. As a software developer
2. I need to create manual tests of the features 
3. So that I deliver increments with good performance

## Acceptance criteria

- [ ] revise and check the tests that Nastja implemented
- [ ] succesfully update tests

## Definition of done

- Can be demoed
- Fully tested with the unit test
- Code well structured and formatted (hold to code conventions)
- Clear explaination of code
- No syntax/runtime errors
- Codes are peerly reviewed
- Communicate issues by leaving comments on github

**Comment by teanas** [comment]
You can manually enable the searcher in the settings (Settings - Issues - Custom Fields - under Actions of the respective custom field choose Edit - Choose the desired Search template) 
Works for the JIRA searcher, but not for our Request overview

**Comment by teanas** [comment]
After a group discussion, decided to enhance the readme with the instructions
