### ISSUE TITLE
Implement Type button in Request Overview

### ISSUE THREAD

**Issue by emiliakaf** [amosproj/amos2021ws02-agile-trans-jira#95]
## User story
1. As a user
2. I need to choose one or more issue types
3. So that I can narrow my query only to issue types I need

## Acceptance criteria

- [ ] when clicking on the type button a dropdow of the issue types is shown
- [ ]  one or more issue types can be checked
![image](https://user-images.githubusercontent.com/92568413/146357077-6ca18029-7c5f-4289-9147-1ce97e471154.png)

- [ ] once an issue type has been selected, the name of the button is changed (see screenshot)
![image](https://user-images.githubusercontent.com/92568413/146357218-4e1add15-fad0-4998-9c57-9ea1a457bca8.png)

## Definition of done
* Can be demoed
* Fully tested with the unit test
* Code well structured and formatted (hold to code conventions)
* Clear explaination of code
* No syntax/runtime errors
* Codes are peerly reviewed
* Communicate issues by leaving comments on github

**Comment by romankupkovic** [comment]
Issue proposal: Rework droppdown query generation from name injection. Right now there cannot be design changes made to dropdown query easily as it disrupts the query. Can be addressed in future issue.
