### ISSUE TITLE
Implement Status button in Request Overview

### ISSUE THREAD

**Issue by emiliakaf** [amosproj/amos2021ws02-agile-trans-jira#96]
## User story
1. As a user 
2. I need to select Status 
3. So that I can narrow down the results with issues which have a status e.g done

## Acceptance criteria

- [ ] button Status has been added between the type and assignee button (currently missing)
- [ ]  when clicking on status a dropdown menu with the all status types is shown

- [ ] one or more status types can be selected

![image](https://user-images.githubusercontent.com/92568413/146357688-535836f0-0fec-4cc2-8884-509bdf923384.png)

- [ ] button changes its name to the status which has been selected
![image](https://user-images.githubusercontent.com/92568413/146358265-38c5a66b-f7ba-401e-88be-4c9b77bce1e8.png)

## Definition of done
* Can be demoed
* Fully tested with the unit test
* Code well structured and formatted (hold to code conventions)
* Clear explaination of code
* No syntax/runtime errors
* Codes are peerly reviewed
* Communicate issues by leaving comments on github

**Comment by romankupkovic** [comment]
Issue proposal: Rework droppdown query generation from name injection. Right now there cannot be design changes made to dropdown query easily as it disrupts the query. Can be addressed in future issue.
