### ISSUE TITLE
Implement More button in Request Overview

### ISSUE THREAD

**Issue by emiliakaf** [amosproj/amos2021ws02-agile-trans-jira#98]
## User story
1. As a user
2. I need to select further search criterias
3. So that I can narrow further the search 

## Acceptance criteria

- [ ] when clicking on More a dropdown menu with following search criteria is shown:
- Requested Time
- Requested Team
- Epic Link
![tempsnip](https://user-images.githubusercontent.com/92568413/148103434-6d7b66e8-55b7-49d6-a85b-1e0f10d18589.png)

- [ ] one or more search criteria can be applied

## Definition of done
* Can be demoed
(* Fully tested with the unit test)
* Code well structured and formatted (hold to code conventions)
* Clear explaination of code
* No syntax/runtime errors
* Codes are peerly reviewed
* Communicate issues by leaving comments on github

**Comment by teanas** [comment]
change the names in accordance to the custom fields (Requested Time -> Start of Work & End of Work; Requested Team -> Associated Team)
