### ISSUE TITLE
Implement Assignee button in Request Overview 

### ISSUE THREAD

**Issue by emiliakaf** [amosproj/amos2021ws02-agile-trans-jira#99]
## User story
As a user
I need to select assignee as a search criteria
So that I can narrow the search only to the issues assigned to a particular assignee.

## Acceptance criteria

- [ ] when clicking on Assigness a dropdown menu with proposed assignees is shown

- [ ]  one or moreAssignees can be selected

![image](https://user-images.githubusercontent.com/92568413/148102388-af5ceef6-a966-40d8-983b-872a1acb3164.png)

## Definition of done
* Can be demoed
* Fully tested with the unit test
* Code well structured and formatted (hold to code conventions)
* Clear explaination of code
* No syntax/runtime errors
* Codes are peerly reviewed
* Communicate issues by leaving comments on github

**Comment by romankupkovic** [comment]
Dropdown now shows all assignable users. if too many users, the options should be limited. could be limited after dropdown search is implemented.
